### ISSUE TITLE
Ingress v1 API Required Update

### ISSUE THREAD

**Issue by rodriggj** [rodriggj/middleware-proto#6]

**Comment by rodriggj** [comment]
When running skaffold dev in the upcoming lecture, you may encounter a warning or error about the v1beta1 API version that is being used.

The v1 Ingress API is now required as of Kubernetes v1.22 and the v1beta1 will no longer work.

A few very minor changes are needed:

https://kubernetes.io/docs/concepts/services-networking/ingress/

1. A [pathType](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) needs to be added

2. How we specify the backend service name and port has changed

3. The kubernetes.io/ingress.class annotation should be removed and replaced by the ingressClassName field under the spec.

4. Replace Prefix PathType with ImplementationSpecific. This is important for any future routes we will define later in the course. For all paths that make use of a regex, you would use ImplementationSpecific instead of Prefix.

**Comment by rodriggj** [comment]
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
```
